### ISSUE TITLE
Some currency values appear incorrectly and cause errors

### ISSUE THREAD

**Issue by userresearcher** [ministryofjustice/apvs-asynchronous-worker#120]
Entered values where the last digit is a zero, such as 18.70 and 1.20, appear incorrectly in claim summary and cause errors accordingly. The examples given appear as "18.7" and "1.2". If these are approved this causes a currency wrong format error requiring user to approve a different amount and correct the format. 

For example see this claim: https://test-apvs-internal-web.kainos.com/claim/89

In addition to a fix here, it is suggested to tolerate values abbreviated by the user and convert them. So if the user enters 5.5, this should appear 5.50.

**Comment by gdouglas1** [comment]
Hi Paul, checked on test this morning and this issue seems to be resolved.  Can you retest and close this task if the issue is resolved for you?

**Comment by userresearcher** [comment]
Yep looks fine now - thank you
