### ISSUE TITLE
Entering sort code with hyphen generates errors

### ISSUE THREAD

**Issue by userresearcher** [ministryofjustice/apvs-asynchronous-worker#121]
Sort codes are frequently displayed with hyphens in between two digits such as 12-34-56, particularly on cheques and account panels. In our research, users frequently try to enter values in this format which creates an error. None have failed to realise why and correct the entry, but it would be far preferable for the system to do this than the user.

If the system could strip out unnecessary and unwanted characters prior to submission, this may help users enter in a format they are more familiar with, particularly if they are copying from another document such as cheque book.

**Comment by pwright08** [comment]
Another solution may be to have 3 separate boxes, and possibly separated by
hyphens

**Comment by userresearcher** [comment]
Hi Paul,

Yes that might help understanding but as it’s much simpler to type into a single field, I would encourage us to maintain this approach. It’s far more an issue on portable devices where people cannot tab between fields so easily and people often don’t click properly in a field. A single field for sort code is by far the preferred approach for such people.

Thank you

Paul

**Comment by pwright08** [comment]
@userresearcher Paul, this should be resolved now if you want to try it on the test environment

**Comment by userresearcher** [comment]
Hi Paul - yep seems to work fine now. Users will thank you for it!
