### ISSUE TITLE
Auto-approval fails for claims submitted on the same day

### ISSUE THREAD

**Issue by stevenalexander** [ministryofjustice/apvs-asynchronous-worker#54]
If a user submits one claim on a day and it is approved, if they submit another claim for same day with same expenses (meeting auto-approval criteria) it will not be auto-approved.

This is due to the logic which looks for claims < DateOfVisit, so claims on the same day (or future) will be used as the last manually approved claim.

**Comment by stevenalexander** [comment]
Confirmed with Chirag that DateOfVisit should not be used to find the last approved claim, we should not care what order/date for the previous claims when looking for the last manually approved claim.

**Comment by gdouglas1** [comment]
Holding off on this one until https://github.com/ministryofjustice/apvs-internal-web/issues/111 is complete
