### ISSUE TITLE
has-claimed-less-than-max-times-this-year auto approval check doesn't retrieve correct number of claims for the year

### ISSUE THREAD

**Issue by pwright08** [ministryofjustice/apvs-asynchronous-worker#68]
To reproduce:

1. set max number of claims per year to 2
1. make FT claim
2. approve
3. make repeat duplicate claim (auto approved)
4. make another repeat duplicate claim

The third claim should fail if the max number of claims is set to 2, but it doesn't seem to count the first manually approved claim in the total number of claims for the year.

**Comment by gdouglas1** [comment]
Make sure to check for the same issue in has-claimed-less-than-max-times-this-month check
