### ISSUE TITLE
If last claim was manual and is not yet approved, the expense items do not show up in the last claim expense screen

### ISSUE THREAD

**Issue by pwright08** [ministryofjustice/apvs-asynchronous-worker#74]
There is a configurable check for auto approval, `is-latest-manual-claim-approved`.

Should the option of making a repeat claim even when the latest manual claim is not yet approved be supported?

Currently we hide the button on the external site to make a repeat claim if a claim/the last claim (needs verification as to which one) has not been approved. The expense items are also not available even if this button is bypassed using the URL.

**Comment by pwright08** [comment]
Given that there is a configurable check `is-latest-manual-claim-approved`, I assume the option of making a repeat claim even when the latest manual claim is not yet approved

**Comment by gdouglas1** [comment]
I think the other scenario is when the previous claim is rejected.  In that case, auto approval should definitely fail.  

The code that controls showing/hiding this button will only show the button if there are no currently in-progress claims associated to the claimant ie. all associated claims do **not** have a claim status of APPROVED, AUTO-APPROVED, REJECTED

**Comment by psoleckimoj** [comment]
Closing.
