### ISSUE TITLE
Prerequisite checks for auto approval do not insert claim events with failure reason if length is too long

### ISSUE THREAD

**Issue by pwright08** [ministryofjustice/apvs-asynchronous-worker#75]

**Comment by pwright08** [comment]
This is because we can only store 250 characters in the ClaimEvent Note column.

The note I was trying to store was 327 characters long. We should increase the length of the Note column, perhaps to the max that knex migration will allow (2000)

**Comment by gdouglas1** [comment]
Integration test fails - there is a function that is trying to retrieve the PaymentAmount using the old column name.
